package com.parkmate.parking_lot.enums;

public enum ParkingLotStatus {
    PENDING, UNDER_SURVEY,PREPARING, PARTNER_CONFIGURATION, ACTIVE_PENDING, ACTIVE, MAP_DENIED, REJECTED,INACTIVE, UNDER_MAINTENANCE, DENIED;
}
