package com.parkmate.parking_lot.enums;

public enum ParkingLotStatus {
    PENDING, PREPARING, PARTNER_CONFIGURATION, PENDING_PAYMENT, ACTIVE, MAP_DENIED, REJECTED, INACTIVE, UNDER_MAINTENANCE, DENIED;
}
