version: '3.8'

x-common-env: &common-env
  DATABASE_HOST : ${DATABASE_HOST}
  DATABASE_USERNAME: ${DATABASE_USERNAME}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  CONFIG_HOST: ${CONFIG_HOST}
  CONFIG_PORT: ${CONFIG_PORT}
  EUREKA_PORT: ${EUREKA_PORT}
  EUREKA_HOST: ${EUREKA_HOST}

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d

  config-service:
    build: ./config-service
    container_name: config-service
    environment:

      <<: *common-env
    ports:
      - "8888:8888"
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8888/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s
    restart: unless-stopped

  eureka-service:
    build: ./eureka-service
    container_name: eureka-service
    depends_on:
      config-service:
        condition: service_healthy
    environment:
      EUREKA_PORT: ${EUREKA_PORT}
      <<: *common-env
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8888/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s
    ports:
      - "9999:9999"

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    depends_on:
      config-service:
        condition: service_healthy
      eureka-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      <<: *common-env
    ports:
      - "8080:8080"
    restart: unless-stopped

  user-service:
    build: ./user-service
    container_name: user-service
    depends_on:
      postgres:
        condition: service_healthy
      config-service:
        condition: service_healthy
      eureka-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      USER_PORT: ${USER_PORT}
      USER_DATABASE: ${USER_DATABASE}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_EXPIRATION: ${JWT_ACCESS_EXPIRATION}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}
      <<: *common-env
    ports:
      - "8081:8080"
    restart: unless-stopped

  parking-lot-service:
    build: ./parking-lot-service
    container_name: parking-lot-service
    depends_on:
      postgres:
        condition: service_healthy
      config-service:
        condition: service_healthy
      eureka-service:
        condition: service_healthy
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker  # Fixed typo
      PARKING_DATABASE: ${PARKING_DATABASE}
      PARKING_LOT_PORT: ${PARKING_LOT_PORT}
      <<: *common-env
    restart: unless-stopped