eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5

  instance:
    hostname: ${HOSTNAME:localhost}
    instance-id: ${spring.application.name}:${HOSTNAME:localhost}:${server.port}

gateway:
  url: ${GATEWAY_URL:http://localhost:8080}