eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/
    registry-fetch-interval-seconds: 3
    initial-instance-info-replication-interval-seconds: 3
    disable-delta: false
    cache-refresh-executor-thread-pool-size: 2

  instance:
    hostname: ${HOSTNAME:localhost}
    instance-id: ${spring.application.name}:${HOSTNAME:localhost}:${server.port}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10

gateway:
  url: ${GATEWAY_URL:http://localhost:8080}

logging:
  pattern:
    level: "%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]"