server:
  port: ${GATEWAY_PORT:8080}

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        # Auth routes - forward to User Service (no JWT needed)
        - id: auth-routes
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/auth/**
          filters:
            - StripPrefix=0

        # User service protected routes (JWT required)
        - id: user-service-protected
          uri: lb://user-service
          predicates:
            - Path=/api/user-service/**
          filters:
            - StripPrefix=0

        # User swagger
        - id: user-swagger
          uri: lb://user-service
          predicates:
            - Path=/aggregate/user-service/v3/api-docs
          filters:
            - SetPath=/api-docs

        # Parking lot service protected routes (JWT required)
        - id: parking-lot-service-protected
          uri: lb://parking-lot-service
          predicates:
            - Path=/api/v1/parking-lot-service/**
          filters:
            - StripPrefix=0

        # Parking lot swagger
        - id: parking-lot-swagger
          uri: lb://parking-lot-service
          predicates:
            - Path=/aggregate/parking-lot-service/v3/api-docs
          filters:
            - SetPath=/api-docs

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:parkmate-super-secret-key-that-must-be-at-least-32-characters-long}

# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka

# Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: User Service
        url: /aggregate/user-service/v3/api-docs
      - name: Parking Lot Service
        url: /aggregate/parking-lot-service/v3/api-docs

# Logging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: TRACE
    org.springframework.security.oauth2.jwt: TRACE
    com.parkmate: DEBUG
