server:
  port: ${GATEWAY_PORT:8080}

spring:
  application:
    name: gateway-service

  cloud:
    loadbalancer:
      cache:
        enabled: false
      ribbon:
        enabled: false

    gateway:
      routes:


        # ============================================
        # USER SERVICE ROUTES
        # ============================================
        - id: user-service-routes
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user-service/**
          filters:
            - StripPrefix=0

        # User service swagger
        - id: user-swagger
          uri: lb://user-service
          predicates:
            - Path=/aggregate/user-service/v3/api-docs
          filters:
            - SetPath=/v3/api-docs

        # User service actuator
        - id: user-actuator
          uri: lb://user-service
          predicates:
            - Path=/actuator/**
          filters:
            - StripPrefix=0

        # ============================================
        # PARKING LOT SERVICE ROUTES - Protected
        # ============================================

        # Catch-all for other parking-lot-service routes
        - id: parking-lot-service-protected
          uri: lb://parking-lot-service
          predicates:
            - Path=/api/v1/parking-service/**
          filters:
            - StripPrefix=0

        # Parking lot swagger
        - id: parking-lot-swagger
          uri: lb://parking-lot-service
          predicates:
            - Path=/aggregate/parking-lot-service/v3/api-docs
          filters:
            - SetPath=/v3/api-docs

      # ============================================
      # GLOBAL CORS
      # ============================================
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
        add-to-simple-url-handler-mapping: true

      # ============================================
      # DEFAULT FILTERS
      # ============================================
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:parkmate-super-secret-key-that-must-be-at-least-32-characters-long}
  expiration: 86400000

# Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: User Service
        url: /aggregate/user-service/v3/api-docs
      - name: Parking Lot Service
        url: /aggregate/parking-lot-service/v3/api-docs
    tryItOutEnabled: true
    operationsSorter: method
    tagsSorter: alpha
    override-with-generic-response: false
    model-and-view-allowed: true
    modelsSorter: none


# Logging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE
    org.springframework.security: DEBUG
    org.springframework.web.cors: DEBUG
    com.parkmate: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Actuator for Gateway
management:
  endpoints:
    web:
      exposure:
        include: gateway, health, info, mappings
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always