server:
  port: ${PARKING_LOT_PORT}

spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:5432/${PARKING_DATABASE:PARKING_DATABASE}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
      enabled: true

  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 500
        order_inserts: true
        order_updates: true

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    disable-swagger-default-url: true
    URLs:
      - name: User Service via Gateway
        url: /v3/api-docs
  use-management-port: false
  show-actuator: false

aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME:your-bucket-name}
    region: ${AWS_REGION:us-east-1}
    accessKeyId: ${AWS_ACCESS_KEY:your-access-key}
    secretAccessKey: ${AWS_SECRET_KEY:your-secret-key}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    tags:
      application: parking-lot-service
    export:
      prometheus:
        enabled: true

  observations:
    key-values:
      application: parking-lot-service
    # ADD THESE - Enable HTTP observations
    http:
      server:
        requests:
          enabled: true
    annotations:
      enabled: true

  tracing:
    sampling:
      probability: 1.0
    enabled: true  # ADD THIS

  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_URL:http://localhost:9411}/api/v2/spans

# ADD LOGGING PATTERN WITH TRACE IDs
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    root: INFO
    com.parkmate: DEBUG
    io.micrometer.tracing: DEBUG  # Temporary - to see tracing activity