spring:
  application:
    name: eureka-service

  config:
    import: configserver:http://${CONFIG_HOST:localhost}:${CONFIG_PORT}

  cloud:
    config:
      fail-fast: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false